apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: webproxy
    name: webproxy
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: webproxy
    name: webproxy
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        description: Webproxy Docker image
        tags: webproxy
      from:
        kind: DockerImage
        name: webproxy:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: webproxy
    name: webproxy-docker-build
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: webproxy:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: .
      git:
        ref: main
        uri: https://github.com/InnovateUKGitHub/openshift-webproxy.git
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
      type: Docker
    triggers:
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: webproxy
    name: webproxy
  spec:
    replicas: 1
    selector:
      name: webproxy
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          name: webproxy
      spec:
        containers:
        - image: ' '
          imagePullPolicy: IfNotPresent
          name: webproxy
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              memory: 1Gi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - webproxy
        from:
          kind: ImageStreamTag
          name: webproxy:latest
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: webproxy
    name: webproxy
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: "8080"
    selector:
      name: webproxy
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: webproxy
    name: webproxy
  spec:
    host: ""
    tls:
      termination: edge
    to:
      kind: Service
      name: webproxy
      weight: 100
    wildcardPolicy: None
  status:
    ingress: null
kind: List
metadata: {}
