- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${APPLICATION_BUILDER_NAME}-docker-build"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    triggers:
      - type: ImageChange
        imageChange: {}
      - type: ConfigChange
    source:
      type: Git
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
      contextDir: ${DOCKERFILE_PATH}
    strategy:
      dockerStrategy:
        dockerfilePath: ${DOCKERFILE_NAME}
    output:
      to:
        kind: "ImageStreamTag"
        name: "${APPLICATION_BUILDER_NAME}:latest"
    resources: {}
    postCommit: {}

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}-docker-build"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    triggers:
      - type: ImageChange
        imageChange: {}
      - type: ConfigChange
    strategy:
      sourceStrategy:
        from:
          kind: "ImageStreamTag"
          name: "${APPLICATION_BUILDER_NAME}:latest"
        forcePull: true
    output:
      to:
        kind: "ImageStreamTag"
        name: "${APPLICATION_NAME}:latest"
    resources: {}
    postCommit: {}
